### ISSUE TITLE
Issue with observer

### ISSUE THREAD

**Issue by catchvarun25** [stuffrabbit/iCoAP#2]
Hey Wojtek ,

Nice work building up iCoAP !!

I am facing one issue while using observer. Below is my code for creating CoAP message for observer
---------------
    ICoAPMessage *cO = [[ICoAPMessage alloc] initAsRequestConfirmable:YES
                                                        requestMethod:IC_GET
                                                            sendToken:YES
                                                              payload:@""];
    
    [cO addOption:IC_URI_PATH withValue:self.textField.text];
     [cO addOption:IC_OBSERVE withValue:@""];
------------

When observer starts it returns me payload in 4 Packets which i club together to form my complete JSON. But when i changed the resource at server endpoint, i get only 1 or 2 Packets i.e. incomplete response. As if some of the packets lost in between transmission.

**Comment by stuffrabbit** [comment]
Hey catchvarun25, 
thank you for using iCoAP!

Hmm, so if I get this right you are trying to transfer large data in multiple observe notifications? 
You have to keep in mind that an observe-message reordering is performed by iCoAP (and any other CoAP client which conforms to RFC 7252), meaning that only the lastest observe notification is delivered to the delegate implementing the ICoAPExchange., i.e. if your notifications arrive out of order (possible due to UDP) you won't receive all packages, as "older" notifications are filtered out automatically (this is the purpose of observe).

I would recommend to use block-transfer in your situation (Block2 option in particular) to transfer large data.

Correct me, if I misunderstood something.

Greetings

Wojtek

(PS: Check out my new CoAP library in Swift, which provides more features: https://github.com/stuffrabbit/SwiftCoAP)

**Comment by catchvarun25** [comment]
Do you mean to say observer-message reordering for us is handled automatically by iCoAP? If yes, i can see wrong reordering , because i'm getting the wrong latest observer notification. Could you please check or reply if my understanding is wrong.

**Comment by stuffrabbit** [comment]
Exactly, iCoAP handles this automatically. It is implemented in `ICoAPExchange.m` line 347 and following:

```objc
        if ((observeOptionValue < currentObserveValue && currentObserveValue - observeOptionValue < kMaxObserveOptionValue) ||
            (observeOptionValue > currentObserveValue && observeOptionValue - currentObserveValue > kMaxObserveOptionValue) ||
            [recentNotificationDate compare:[cO.timestamp dateByAddingTimeInterval:128.0]] == NSOrderedAscending) {
            
            recentNotificationDate = cO.timestamp;
            observeOptionValue = currentObserveValue;
        }
        else {
            return;
        }
```
This filtering mechanism is implemented as described in the observe-draft 14 in section  3.4 (https://tools.ietf.org/html/draft-ietf-core-observe-16#section-3.4).
It's been a while since I implemented that, but I believe that it worked correctly.  It is important that your latest notification has a bigger option value than the previous ones (please refer to the draft).
